// Code generated by Fern. DO NOT EDIT.

package facebookads

import (
	context "context"
	fmt "fmt"
	http "net/http"
	strconv "strconv"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get list of Facebook ads.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListFacebookAdsRequest{}
//	client.FacebookAds.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListFacebookAdsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.FacebookAds, *mailchimpmarketinggosdk.ListFacebookAdsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/facebook-ads"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListFacebookAdsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.FacebookAds, *mailchimpmarketinggosdk.ListFacebookAdsResponse] {
		next += 1
		results := response.GetFacebookAds()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.FacebookAds, *mailchimpmarketinggosdk.ListFacebookAdsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Get details of a Facebook ad.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetFacebookAdsRequest{
//	    OutreachID: "outreach_id",
//	}
//	client.FacebookAds.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetFacebookAdsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.FacebookAds, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
