// Code generated by Fern. DO NOT EDIT.

package accountexports

import (
	context "context"
	fmt "fmt"
	http "net/http"
	strconv "strconv"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get a list of account exports for a given account.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListAccountExportsRequest{}
//	client.AccountExports.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListAccountExportsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ListAccountExportsResponseExportsItem, *mailchimpmarketinggosdk.ListAccountExportsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/account-exports"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListAccountExportsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ListAccountExportsResponseExportsItem, *mailchimpmarketinggosdk.ListAccountExportsResponse] {
		next += 1
		results := response.GetExports()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ListAccountExportsResponseExportsItem, *mailchimpmarketinggosdk.ListAccountExportsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Create a new account export in your Mailchimp account.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateAccountExportsRequest{
//	    IncludeStages: []mailchimpmarketinggosdk.CreateAccountExportsRequestIncludeStagesItem{
//	        mailchimpmarketinggosdk.CreateAccountExportsRequestIncludeStagesItemAudiences,
//	        mailchimpmarketinggosdk.CreateAccountExportsRequestIncludeStagesItemGalleryFiles,
//	    },
//	}
//	client.AccountExports.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateAccountExportsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.CreateAccountExportsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific account export.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetAccountExportsRequest{
//	    ExportID: "export_id",
//	}
//	client.AccountExports.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetAccountExportsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.GetAccountExportsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
