// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	big "math/big"
)

var (
	listSearchCampaignsRequestFieldFields        = big.NewInt(1 << 0)
	listSearchCampaignsRequestFieldExcludeFields = big.NewInt(1 << 1)
	listSearchCampaignsRequestFieldQuery         = big.NewInt(1 << 2)
)

type ListSearchCampaignsRequest struct {
	// A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.
	Fields []*string `json:"-" url:"fields,omitempty"`
	// A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.
	ExcludeFields []*string `json:"-" url:"exclude_fields,omitempty"`
	// The search query used to filter results.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSearchCampaignsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsRequest) SetFields(fields []*string) {
	l.Fields = fields
	l.require(listSearchCampaignsRequestFieldFields)
}

// SetExcludeFields sets the ExcludeFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsRequest) SetExcludeFields(excludeFields []*string) {
	l.ExcludeFields = excludeFields
	l.require(listSearchCampaignsRequestFieldExcludeFields)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsRequest) SetQuery(query string) {
	l.Query = query
	l.require(listSearchCampaignsRequestFieldQuery)
}

// Campaigns and Snippets found for given search term.
var (
	listSearchCampaignsResponseFieldLinks      = big.NewInt(1 << 0)
	listSearchCampaignsResponseFieldResults    = big.NewInt(1 << 1)
	listSearchCampaignsResponseFieldTotalItems = big.NewInt(1 << 2)
)

type ListSearchCampaignsResponse struct {
	// A list of link types and descriptions for the API schema documents.
	Links []*ListSearchCampaignsResponseLinksItem `json:"_links,omitempty" url:"_links,omitempty"`
	// An array of matching campaigns and snippets.
	Results []*ListSearchCampaignsResponseResultsItem `json:"results,omitempty" url:"results,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems *int `json:"total_items,omitempty" url:"total_items,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSearchCampaignsResponse) GetLinks() []*ListSearchCampaignsResponseLinksItem {
	if l == nil {
		return nil
	}
	return l.Links
}

func (l *ListSearchCampaignsResponse) GetResults() []*ListSearchCampaignsResponseResultsItem {
	if l == nil {
		return nil
	}
	return l.Results
}

func (l *ListSearchCampaignsResponse) GetTotalItems() *int {
	if l == nil {
		return nil
	}
	return l.TotalItems
}

func (l *ListSearchCampaignsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSearchCampaignsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponse) SetLinks(links []*ListSearchCampaignsResponseLinksItem) {
	l.Links = links
	l.require(listSearchCampaignsResponseFieldLinks)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponse) SetResults(results []*ListSearchCampaignsResponseResultsItem) {
	l.Results = results
	l.require(listSearchCampaignsResponseFieldResults)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponse) SetTotalItems(totalItems *int) {
	l.TotalItems = totalItems
	l.require(listSearchCampaignsResponseFieldTotalItems)
}

func (l *ListSearchCampaignsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSearchCampaignsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSearchCampaignsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSearchCampaignsResponse) MarshalJSON() ([]byte, error) {
	type embed ListSearchCampaignsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSearchCampaignsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// This object represents a link from the resource where it is found to another resource or action that may be performed.
var (
	listSearchCampaignsResponseLinksItemFieldHref         = big.NewInt(1 << 0)
	listSearchCampaignsResponseLinksItemFieldMethod       = big.NewInt(1 << 1)
	listSearchCampaignsResponseLinksItemFieldRel          = big.NewInt(1 << 2)
	listSearchCampaignsResponseLinksItemFieldSchema       = big.NewInt(1 << 3)
	listSearchCampaignsResponseLinksItemFieldTargetSchema = big.NewInt(1 << 4)
)

type ListSearchCampaignsResponseLinksItem struct {
	// This property contains a fully-qualified URL that can be called to retrieve the linked resource or perform the linked action.
	Href *string `json:"href,omitempty" url:"href,omitempty"`
	// The HTTP method that should be used when accessing the URL defined in 'href'.
	Method *ListSearchCampaignsResponseLinksItemMethod `json:"method,omitempty" url:"method,omitempty"`
	// As with an HTML 'rel' attribute, this describes the type of link.
	Rel *string `json:"rel,omitempty" url:"rel,omitempty"`
	// For HTTP methods that can receive bodies (POST and PUT), this is a URL representing the schema that the body should conform to.
	Schema *string `json:"schema,omitempty" url:"schema,omitempty"`
	// For GETs, this is a URL representing the schema that the response should conform to.
	TargetSchema *string `json:"targetSchema,omitempty" url:"targetSchema,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSearchCampaignsResponseLinksItem) GetHref() *string {
	if l == nil {
		return nil
	}
	return l.Href
}

func (l *ListSearchCampaignsResponseLinksItem) GetMethod() *ListSearchCampaignsResponseLinksItemMethod {
	if l == nil {
		return nil
	}
	return l.Method
}

func (l *ListSearchCampaignsResponseLinksItem) GetRel() *string {
	if l == nil {
		return nil
	}
	return l.Rel
}

func (l *ListSearchCampaignsResponseLinksItem) GetSchema() *string {
	if l == nil {
		return nil
	}
	return l.Schema
}

func (l *ListSearchCampaignsResponseLinksItem) GetTargetSchema() *string {
	if l == nil {
		return nil
	}
	return l.TargetSchema
}

func (l *ListSearchCampaignsResponseLinksItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSearchCampaignsResponseLinksItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetHref sets the Href field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponseLinksItem) SetHref(href *string) {
	l.Href = href
	l.require(listSearchCampaignsResponseLinksItemFieldHref)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponseLinksItem) SetMethod(method *ListSearchCampaignsResponseLinksItemMethod) {
	l.Method = method
	l.require(listSearchCampaignsResponseLinksItemFieldMethod)
}

// SetRel sets the Rel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponseLinksItem) SetRel(rel *string) {
	l.Rel = rel
	l.require(listSearchCampaignsResponseLinksItemFieldRel)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponseLinksItem) SetSchema(schema *string) {
	l.Schema = schema
	l.require(listSearchCampaignsResponseLinksItemFieldSchema)
}

// SetTargetSchema sets the TargetSchema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponseLinksItem) SetTargetSchema(targetSchema *string) {
	l.TargetSchema = targetSchema
	l.require(listSearchCampaignsResponseLinksItemFieldTargetSchema)
}

func (l *ListSearchCampaignsResponseLinksItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSearchCampaignsResponseLinksItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSearchCampaignsResponseLinksItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSearchCampaignsResponseLinksItem) MarshalJSON() ([]byte, error) {
	type embed ListSearchCampaignsResponseLinksItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSearchCampaignsResponseLinksItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The HTTP method that should be used when accessing the URL defined in 'href'.
type ListSearchCampaignsResponseLinksItemMethod string

const (
	ListSearchCampaignsResponseLinksItemMethodGet     ListSearchCampaignsResponseLinksItemMethod = "GET"
	ListSearchCampaignsResponseLinksItemMethodPost    ListSearchCampaignsResponseLinksItemMethod = "POST"
	ListSearchCampaignsResponseLinksItemMethodPut     ListSearchCampaignsResponseLinksItemMethod = "PUT"
	ListSearchCampaignsResponseLinksItemMethodPatch   ListSearchCampaignsResponseLinksItemMethod = "PATCH"
	ListSearchCampaignsResponseLinksItemMethodDelete  ListSearchCampaignsResponseLinksItemMethod = "DELETE"
	ListSearchCampaignsResponseLinksItemMethodOptions ListSearchCampaignsResponseLinksItemMethod = "OPTIONS"
	ListSearchCampaignsResponseLinksItemMethodHead    ListSearchCampaignsResponseLinksItemMethod = "HEAD"
)

func NewListSearchCampaignsResponseLinksItemMethodFromString(s string) (ListSearchCampaignsResponseLinksItemMethod, error) {
	switch s {
	case "GET":
		return ListSearchCampaignsResponseLinksItemMethodGet, nil
	case "POST":
		return ListSearchCampaignsResponseLinksItemMethodPost, nil
	case "PUT":
		return ListSearchCampaignsResponseLinksItemMethodPut, nil
	case "PATCH":
		return ListSearchCampaignsResponseLinksItemMethodPatch, nil
	case "DELETE":
		return ListSearchCampaignsResponseLinksItemMethodDelete, nil
	case "OPTIONS":
		return ListSearchCampaignsResponseLinksItemMethodOptions, nil
	case "HEAD":
		return ListSearchCampaignsResponseLinksItemMethodHead, nil
	}
	var t ListSearchCampaignsResponseLinksItemMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListSearchCampaignsResponseLinksItemMethod) Ptr() *ListSearchCampaignsResponseLinksItemMethod {
	return &l
}

var (
	listSearchCampaignsResponseResultsItemFieldCampaign = big.NewInt(1 << 0)
	listSearchCampaignsResponseResultsItemFieldSnippet  = big.NewInt(1 << 1)
)

type ListSearchCampaignsResponseResultsItem struct {
	Campaign *Campaigns `json:"campaign,omitempty" url:"campaign,omitempty"`
	Snippet  *string    `json:"snippet,omitempty" url:"snippet,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSearchCampaignsResponseResultsItem) GetCampaign() *Campaigns {
	if l == nil {
		return nil
	}
	return l.Campaign
}

func (l *ListSearchCampaignsResponseResultsItem) GetSnippet() *string {
	if l == nil {
		return nil
	}
	return l.Snippet
}

func (l *ListSearchCampaignsResponseResultsItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSearchCampaignsResponseResultsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCampaign sets the Campaign field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponseResultsItem) SetCampaign(campaign *Campaigns) {
	l.Campaign = campaign
	l.require(listSearchCampaignsResponseResultsItemFieldCampaign)
}

// SetSnippet sets the Snippet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSearchCampaignsResponseResultsItem) SetSnippet(snippet *string) {
	l.Snippet = snippet
	l.require(listSearchCampaignsResponseResultsItemFieldSnippet)
}

func (l *ListSearchCampaignsResponseResultsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSearchCampaignsResponseResultsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSearchCampaignsResponseResultsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSearchCampaignsResponseResultsItem) MarshalJSON() ([]byte, error) {
	type embed ListSearchCampaignsResponseResultsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSearchCampaignsResponseResultsItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
