// Code generated by Fern. DO NOT EDIT.

package lists_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	client "github.com/mailchimp/mailchimp-marketing-go-sdk/client"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestListsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListListsRequest{}
	_, invocationErr := client.Lists.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListWithWireMock", "GET", "/3.0/lists", nil, 1)
}

func TestListsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateListsRequest{
		CampaignDefaults: &mailchimpmarketinggosdk.CreateListsRequestCampaignDefaults{
			FromEmail: "from_email",
			FromName:  "from_name",
			Language:  "language",
			Subject:   "subject",
		},
		Contact: &mailchimpmarketinggosdk.CreateListsRequestContact{
			Address1: "address1",
			City:     "city",
			Company:  "company",
			Country:  "country",
		},
		EmailTypeOption:    true,
		Name:               "name",
		PermissionReminder: "permission_reminder",
	}
	_, invocationErr := client.Lists.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateWithWireMock", "POST", "/3.0/lists", nil, 1)
}

func TestListsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetWithWireMock", "GET", "/3.0/lists/list_id", nil, 1)
}

func TestListsBatchSubscribeOrUnsubscribeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.BatchSubscribeOrUnsubscribeListsRequest{
		ListID:  "list_id",
		Members: []*mailchimpmarketinggosdk.BatchSubscribeOrUnsubscribeListsRequestMembersItem{},
	}
	_, invocationErr := client.Lists.BatchSubscribeOrUnsubscribe(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsBatchSubscribeOrUnsubscribeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsBatchSubscribeOrUnsubscribeWithWireMock", "POST", "/3.0/lists/list_id", nil, 1)
}

func TestListsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteListsRequest{
		ListID: "list_id",
	}
	invocationErr := client.Lists.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteWithWireMock", "DELETE", "/3.0/lists/list_id", nil, 1)
}

func TestListsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateWithWireMock", "PATCH", "/3.0/lists/list_id", nil, 1)
}

func TestListsListAbuseReportsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListAbuseReportsListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListAbuseReports(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListAbuseReportsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListAbuseReportsWithWireMock", "GET", "/3.0/lists/list_id/abuse-reports", nil, 1)
}

func TestListsGetAbuseReportWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetAbuseReportListsRequest{
		ListID:   "list_id",
		ReportID: "report_id",
	}
	_, invocationErr := client.Lists.GetAbuseReport(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetAbuseReportWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetAbuseReportWithWireMock", "GET", "/3.0/lists/list_id/abuse-reports/report_id", nil, 1)
}

func TestListsListActivityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListActivityListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListActivity(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListActivityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListActivityWithWireMock", "GET", "/3.0/lists/list_id/activity", nil, 1)
}

func TestListsListClientsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListClientsListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListClients(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListClientsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListClientsWithWireMock", "GET", "/3.0/lists/list_id/clients", nil, 1)
}

func TestListsListGrowthHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListGrowthHistoryListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListGrowthHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListGrowthHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListGrowthHistoryWithWireMock", "GET", "/3.0/lists/list_id/growth-history", nil, 1)
}

func TestListsGetGrowthHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetGrowthHistoryListsRequest{
		ListID: "list_id",
		Month:  "month",
	}
	_, invocationErr := client.Lists.GetGrowthHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetGrowthHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetGrowthHistoryWithWireMock", "GET", "/3.0/lists/list_id/growth-history/month", nil, 1)
}

func TestListsListInterestCategoriesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListInterestCategoriesListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListInterestCategories(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListInterestCategoriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListInterestCategoriesWithWireMock", "GET", "/3.0/lists/list_id/interest-categories", nil, 1)
}

func TestListsCreateInterestCategoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateInterestCategoryListsRequest{
		ListID: "list_id",
		Title:  "title",
		Type:   mailchimpmarketinggosdk.CreateInterestCategoryListsRequestTypeCheckboxes,
	}
	_, invocationErr := client.Lists.CreateInterestCategory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateInterestCategoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateInterestCategoryWithWireMock", "POST", "/3.0/lists/list_id/interest-categories", nil, 1)
}

func TestListsGetInterestCategoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetInterestCategoryListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
	}
	_, invocationErr := client.Lists.GetInterestCategory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetInterestCategoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetInterestCategoryWithWireMock", "GET", "/3.0/lists/list_id/interest-categories/interest_category_id", nil, 1)
}

func TestListsDeleteInterestCategoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteInterestCategoryListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
	}
	invocationErr := client.Lists.DeleteInterestCategory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteInterestCategoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteInterestCategoryWithWireMock", "DELETE", "/3.0/lists/list_id/interest-categories/interest_category_id", nil, 1)
}

func TestListsUpdateInterestCategoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateInterestCategoryListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
	}
	_, invocationErr := client.Lists.UpdateInterestCategory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateInterestCategoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateInterestCategoryWithWireMock", "PATCH", "/3.0/lists/list_id/interest-categories/interest_category_id", nil, 1)
}

func TestListsListInterestCategoryInterestsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListInterestCategoryInterestsListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
	}
	_, invocationErr := client.Lists.ListInterestCategoryInterests(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListInterestCategoryInterestsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListInterestCategoryInterestsWithWireMock", "GET", "/3.0/lists/list_id/interest-categories/interest_category_id/interests", nil, 1)
}

func TestListsCreateInterestCategoryInterestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateInterestCategoryInterestListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
		Name:               "name",
	}
	_, invocationErr := client.Lists.CreateInterestCategoryInterest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateInterestCategoryInterestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateInterestCategoryInterestWithWireMock", "POST", "/3.0/lists/list_id/interest-categories/interest_category_id/interests", nil, 1)
}

func TestListsGetInterestCategoryInterestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetInterestCategoryInterestListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
		InterestID:         "interest_id",
	}
	_, invocationErr := client.Lists.GetInterestCategoryInterest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetInterestCategoryInterestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetInterestCategoryInterestWithWireMock", "GET", "/3.0/lists/list_id/interest-categories/interest_category_id/interests/interest_id", nil, 1)
}

func TestListsDeleteInterestCategoryInterestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteInterestCategoryInterestListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
		InterestID:         "interest_id",
	}
	invocationErr := client.Lists.DeleteInterestCategoryInterest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteInterestCategoryInterestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteInterestCategoryInterestWithWireMock", "DELETE", "/3.0/lists/list_id/interest-categories/interest_category_id/interests/interest_id", nil, 1)
}

func TestListsUpdateInterestCategoryInterestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateInterestCategoryInterestListsRequest{
		ListID:             "list_id",
		InterestCategoryID: "interest_category_id",
		InterestID:         "interest_id",
	}
	_, invocationErr := client.Lists.UpdateInterestCategoryInterest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateInterestCategoryInterestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateInterestCategoryInterestWithWireMock", "PATCH", "/3.0/lists/list_id/interest-categories/interest_category_id/interests/interest_id", nil, 1)
}

func TestListsListLocationsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListLocationsListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListLocations(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListLocationsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListLocationsWithWireMock", "GET", "/3.0/lists/list_id/locations", nil, 1)
}

func TestListsListMembersWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMembersListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListMembers(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMembersWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMembersWithWireMock", "GET", "/3.0/lists/list_id/members", nil, 1)
}

func TestListsCreateMemberWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateMemberListsRequest{
		ListID:       "list_id",
		EmailAddress: "email_address",
		Status:       mailchimpmarketinggosdk.CreateMemberListsRequestStatusSubscribed,
	}
	_, invocationErr := client.Lists.CreateMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateMemberWithWireMock", "POST", "/3.0/lists/list_id/members", nil, 1)
}

func TestListsGetMemberWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetMemberListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.GetMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetMemberWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash", nil, 1)
}

func TestListsUpsertMemberWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpsertMemberListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
		EmailAddress:   "email_address",
	}
	_, invocationErr := client.Lists.UpsertMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpsertMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpsertMemberWithWireMock", "PUT", "/3.0/lists/list_id/members/subscriber_hash", nil, 1)
}

func TestListsDeleteMemberWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteMemberListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	invocationErr := client.Lists.DeleteMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteMemberWithWireMock", "DELETE", "/3.0/lists/list_id/members/subscriber_hash", nil, 1)
}

func TestListsUpdateMemberWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateMemberListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.UpdateMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateMemberWithWireMock", "PATCH", "/3.0/lists/list_id/members/subscriber_hash", nil, 1)
}

func TestListsCreateMemberActionDeletePermanentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateMemberActionDeletePermanentListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	invocationErr := client.Lists.CreateMemberActionDeletePermanent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateMemberActionDeletePermanentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateMemberActionDeletePermanentWithWireMock", "POST", "/3.0/lists/list_id/members/subscriber_hash/actions/delete-permanent", nil, 1)
}

func TestListsListMemberActivityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMemberActivityListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.ListMemberActivity(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMemberActivityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMemberActivityWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash/activity", nil, 1)
}

func TestListsListMemberActivityFeedWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMemberActivityFeedListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.ListMemberActivityFeed(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMemberActivityFeedWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMemberActivityFeedWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash/activity-feed", nil, 1)
}

func TestListsListMemberEventsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMemberEventsListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.ListMemberEvents(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMemberEventsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMemberEventsWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash/events", nil, 1)
}

func TestListsCreateMemberEventWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateMemberEventListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
		Name:           "name",
	}
	invocationErr := client.Lists.CreateMemberEvent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateMemberEventWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateMemberEventWithWireMock", "POST", "/3.0/lists/list_id/members/subscriber_hash/events", nil, 1)
}

func TestListsListMemberGoalsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMemberGoalsListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.ListMemberGoals(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMemberGoalsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMemberGoalsWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash/goals", nil, 1)
}

func TestListsListMemberNotesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMemberNotesListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.ListMemberNotes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMemberNotesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMemberNotesWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash/notes", nil, 1)
}

func TestListsCreateMemberNoteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateMemberNoteListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.CreateMemberNote(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateMemberNoteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateMemberNoteWithWireMock", "POST", "/3.0/lists/list_id/members/subscriber_hash/notes", nil, 1)
}

func TestListsGetMemberNoteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetMemberNoteListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
		NoteID:         "note_id",
	}
	_, invocationErr := client.Lists.GetMemberNote(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetMemberNoteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetMemberNoteWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash/notes/note_id", nil, 1)
}

func TestListsDeleteMemberNoteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteMemberNoteListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
		NoteID:         "note_id",
	}
	invocationErr := client.Lists.DeleteMemberNote(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteMemberNoteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteMemberNoteWithWireMock", "DELETE", "/3.0/lists/list_id/members/subscriber_hash/notes/note_id", nil, 1)
}

func TestListsUpdateMemberNoteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateMemberNoteListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
		NoteID:         "note_id",
	}
	_, invocationErr := client.Lists.UpdateMemberNote(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateMemberNoteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateMemberNoteWithWireMock", "PATCH", "/3.0/lists/list_id/members/subscriber_hash/notes/note_id", nil, 1)
}

func TestListsListMemberTagsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMemberTagsListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
	}
	_, invocationErr := client.Lists.ListMemberTags(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMemberTagsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMemberTagsWithWireMock", "GET", "/3.0/lists/list_id/members/subscriber_hash/tags", nil, 1)
}

func TestListsCreateMemberTagWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateMemberTagListsRequest{
		ListID:         "list_id",
		SubscriberHash: "subscriber_hash",
		Tags: []*mailchimpmarketinggosdk.CreateMemberTagListsRequestTagsItem{
			&mailchimpmarketinggosdk.CreateMemberTagListsRequestTagsItem{
				Name:   "name",
				Status: mailchimpmarketinggosdk.CreateMemberTagListsRequestTagsItemStatusInactive,
			},
		},
	}
	invocationErr := client.Lists.CreateMemberTag(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateMemberTagWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateMemberTagWithWireMock", "POST", "/3.0/lists/list_id/members/subscriber_hash/tags", nil, 1)
}

func TestListsListMergeFieldsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListMergeFieldsListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListMergeFields(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListMergeFieldsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListMergeFieldsWithWireMock", "GET", "/3.0/lists/list_id/merge-fields", nil, 1)
}

func TestListsCreateMergeFieldWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateMergeFieldListsRequest{
		ListID: "list_id",
		Name:   "name",
		Type:   mailchimpmarketinggosdk.CreateMergeFieldListsRequestTypeText,
	}
	_, invocationErr := client.Lists.CreateMergeField(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateMergeFieldWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateMergeFieldWithWireMock", "POST", "/3.0/lists/list_id/merge-fields", nil, 1)
}

func TestListsGetMergeFieldWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetMergeFieldListsRequest{
		ListID:  "list_id",
		MergeID: "merge_id",
	}
	_, invocationErr := client.Lists.GetMergeField(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetMergeFieldWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetMergeFieldWithWireMock", "GET", "/3.0/lists/list_id/merge-fields/merge_id", nil, 1)
}

func TestListsDeleteMergeFieldWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteMergeFieldListsRequest{
		ListID:  "list_id",
		MergeID: "merge_id",
	}
	invocationErr := client.Lists.DeleteMergeField(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteMergeFieldWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteMergeFieldWithWireMock", "DELETE", "/3.0/lists/list_id/merge-fields/merge_id", nil, 1)
}

func TestListsUpdateMergeFieldWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateMergeFieldListsRequest{
		ListID:  "list_id",
		MergeID: "merge_id",
	}
	_, invocationErr := client.Lists.UpdateMergeField(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateMergeFieldWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateMergeFieldWithWireMock", "PATCH", "/3.0/lists/list_id/merge-fields/merge_id", nil, 1)
}

func TestListsListSegmentsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListSegmentsListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListSegments(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListSegmentsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListSegmentsWithWireMock", "GET", "/3.0/lists/list_id/segments", nil, 1)
}

func TestListsCreateSegmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateSegmentListsRequest{
		ListID: "list_id",
		Name:   "name",
	}
	_, invocationErr := client.Lists.CreateSegment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateSegmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateSegmentWithWireMock", "POST", "/3.0/lists/list_id/segments", nil, 1)
}

func TestListsGetSegmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetSegmentListsRequest{
		ListID:    "list_id",
		SegmentID: "segment_id",
	}
	_, invocationErr := client.Lists.GetSegment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetSegmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetSegmentWithWireMock", "GET", "/3.0/lists/list_id/segments/segment_id", nil, 1)
}

func TestListsBatchAddOrRemoveMembersWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.BatchAddOrRemoveMembersListsRequest{
		ListID:    "list_id",
		SegmentID: "segment_id",
	}
	_, invocationErr := client.Lists.BatchAddOrRemoveMembers(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsBatchAddOrRemoveMembersWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsBatchAddOrRemoveMembersWithWireMock", "POST", "/3.0/lists/list_id/segments/segment_id", nil, 1)
}

func TestListsDeleteSegmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteSegmentListsRequest{
		ListID:    "list_id",
		SegmentID: "segment_id",
	}
	invocationErr := client.Lists.DeleteSegment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteSegmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteSegmentWithWireMock", "DELETE", "/3.0/lists/list_id/segments/segment_id", nil, 1)
}

func TestListsUpdateSegmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateSegmentListsRequest{
		ListID:    "list_id",
		SegmentID: "segment_id",
	}
	_, invocationErr := client.Lists.UpdateSegment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateSegmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateSegmentWithWireMock", "PATCH", "/3.0/lists/list_id/segments/segment_id", nil, 1)
}

func TestListsListSegmentMembersWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListSegmentMembersListsRequest{
		ListID:    "list_id",
		SegmentID: "segment_id",
	}
	_, invocationErr := client.Lists.ListSegmentMembers(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListSegmentMembersWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListSegmentMembersWithWireMock", "GET", "/3.0/lists/list_id/segments/segment_id/members", nil, 1)
}

func TestListsCreateSegmentMemberWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateSegmentMemberListsRequest{
		ListID:       "list_id",
		SegmentID:    "segment_id",
		EmailAddress: "email_address",
	}
	_, invocationErr := client.Lists.CreateSegmentMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateSegmentMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateSegmentMemberWithWireMock", "POST", "/3.0/lists/list_id/segments/segment_id/members", nil, 1)
}

func TestListsDeleteSegmentMemberWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteSegmentMemberListsRequest{
		ListID:         "list_id",
		SegmentID:      "segment_id",
		SubscriberHash: "subscriber_hash",
	}
	invocationErr := client.Lists.DeleteSegmentMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteSegmentMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteSegmentMemberWithWireMock", "DELETE", "/3.0/lists/list_id/segments/segment_id/members/subscriber_hash", nil, 1)
}

func TestListsListSignupFormsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListSignupFormsListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListSignupForms(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListSignupFormsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListSignupFormsWithWireMock", "GET", "/3.0/lists/list_id/signup-forms", nil, 1)
}

func TestListsCreateSignupFormWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateSignupFormListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.CreateSignupForm(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateSignupFormWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateSignupFormWithWireMock", "POST", "/3.0/lists/list_id/signup-forms", nil, 1)
}

func TestListsListSurveysWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListSurveysListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListSurveys(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListSurveysWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListSurveysWithWireMock", "GET", "/3.0/lists/list_id/surveys", nil, 1)
}

func TestListsCreateSurveyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateSurveyListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.CreateSurvey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateSurveyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateSurveyWithWireMock", "POST", "/3.0/lists/list_id/surveys", nil, 1)
}

func TestListsGetSurveyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetSurveyListsRequest{
		ListID:   "list_id",
		SurveyID: "survey_id",
	}
	_, invocationErr := client.Lists.GetSurvey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetSurveyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetSurveyWithWireMock", "GET", "/3.0/lists/list_id/surveys/survey_id", nil, 1)
}

func TestListsDeleteSurveyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteSurveyListsRequest{
		ListID:   "list_id",
		SurveyID: "survey_id",
	}
	invocationErr := client.Lists.DeleteSurvey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteSurveyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteSurveyWithWireMock", "DELETE", "/3.0/lists/list_id/surveys/survey_id", nil, 1)
}

func TestListsUpdateSurveyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateSurveyListsRequest{
		ListID:   "list_id",
		SurveyID: "survey_id",
	}
	_, invocationErr := client.Lists.UpdateSurvey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateSurveyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateSurveyWithWireMock", "PATCH", "/3.0/lists/list_id/surveys/survey_id", nil, 1)
}

func TestListsCreateListSurveyActionReplicateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateListSurveyActionReplicateListsRequest{
		ListIDPathParam: "list_id",
		SurveyID:        "survey_id",
	}
	_, invocationErr := client.Lists.CreateListSurveyActionReplicate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateListSurveyActionReplicateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateListSurveyActionReplicateWithWireMock", "POST", "/3.0/lists/list_id/surveys/survey_id/actions/replicate", nil, 1)
}

func TestListsListTagSearchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListTagSearchListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListTagSearch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListTagSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListTagSearchWithWireMock", "GET", "/3.0/lists/list_id/tag-search", nil, 1)
}

func TestListsListWebhooksWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListWebhooksListsRequest{
		ListID: "list_id",
	}
	_, invocationErr := client.Lists.ListWebhooks(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsListWebhooksWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsListWebhooksWithWireMock", "GET", "/3.0/lists/list_id/webhooks", nil, 1)
}

func TestListsCreateWebhookWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateWebhookListsRequest{
		ListID: "list_id",
		Body:   &mailchimpmarketinggosdk.AddWebhook{},
	}
	_, invocationErr := client.Lists.CreateWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsCreateWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsCreateWebhookWithWireMock", "POST", "/3.0/lists/list_id/webhooks", nil, 1)
}

func TestListsGetWebhookWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetWebhookListsRequest{
		ListID:    "list_id",
		WebhookID: "webhook_id",
	}
	_, invocationErr := client.Lists.GetWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsGetWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsGetWebhookWithWireMock", "GET", "/3.0/lists/list_id/webhooks/webhook_id", nil, 1)
}

func TestListsDeleteWebhookWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteWebhookListsRequest{
		ListID:    "list_id",
		WebhookID: "webhook_id",
	}
	invocationErr := client.Lists.DeleteWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsDeleteWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsDeleteWebhookWithWireMock", "DELETE", "/3.0/lists/list_id/webhooks/webhook_id", nil, 1)
}

func TestListsUpdateWebhookWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateWebhookListsRequest{
		ListID:    "list_id",
		WebhookID: "webhook_id",
		Body:      &mailchimpmarketinggosdk.AddWebhook{},
	}
	_, invocationErr := client.Lists.UpdateWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestListsUpdateWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestListsUpdateWebhookWithWireMock", "PATCH", "/3.0/lists/list_id/webhooks/webhook_id", nil, 1)
}
