// Code generated by Fern. DO NOT EDIT.

package campaigns_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	client "github.com/mailchimp/mailchimp-marketing-go-sdk/client"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCampaignsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListCampaignsRequest{}
	_, invocationErr := client.Campaigns.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsListWithWireMock", "GET", "/3.0/campaigns", nil, 1)
}

func TestCampaignsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateCampaignsRequest{
		Type: mailchimpmarketinggosdk.CreateCampaignsRequestTypeRegular,
	}
	_, invocationErr := client.Campaigns.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateWithWireMock", "POST", "/3.0/campaigns", nil, 1)
}

func TestCampaignsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetCampaignsRequest{
		CampaignID: "campaign_id",
	}
	_, invocationErr := client.Campaigns.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsGetWithWireMock", "GET", "/3.0/campaigns/campaign_id", nil, 1)
}

func TestCampaignsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteCampaignsRequest{
		CampaignID: "campaign_id",
	}
	invocationErr := client.Campaigns.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsDeleteWithWireMock", "DELETE", "/3.0/campaigns/campaign_id", nil, 1)
}

func TestCampaignsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateCampaignsRequest{
		CampaignID: "campaign_id",
	}
	_, invocationErr := client.Campaigns.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsUpdateWithWireMock", "PATCH", "/3.0/campaigns/campaign_id", nil, 1)
}

func TestCampaignsCreateActionCancelSendWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionCancelSendCampaignsRequest{
		CampaignID: "campaign_id",
	}
	invocationErr := client.Campaigns.CreateActionCancelSend(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionCancelSendWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionCancelSendWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/cancel-send", nil, 1)
}

func TestCampaignsCreateActionCreateResendWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionCreateResendCampaignsRequest{
		CampaignID: "campaign_id",
	}
	_, invocationErr := client.Campaigns.CreateActionCreateResend(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionCreateResendWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionCreateResendWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/create-resend", nil, 1)
}

func TestCampaignsCreateActionPauseWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionPauseCampaignsRequest{
		CampaignID: "campaign_id",
	}
	invocationErr := client.Campaigns.CreateActionPause(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionPauseWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionPauseWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/pause", nil, 1)
}

func TestCampaignsCreateActionReplicateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionReplicateCampaignsRequest{
		CampaignID: "campaign_id",
	}
	_, invocationErr := client.Campaigns.CreateActionReplicate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionReplicateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionReplicateWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/replicate", nil, 1)
}

func TestCampaignsCreateActionResumeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionResumeCampaignsRequest{
		CampaignID: "campaign_id",
	}
	invocationErr := client.Campaigns.CreateActionResume(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionResumeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionResumeWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/resume", nil, 1)
}

func TestCampaignsCreateActionScheduleWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionScheduleCampaignsRequest{
		CampaignID: "campaign_id",
		ScheduleTime: mailchimpmarketinggosdk.MustParseDateTime(
			"2024-01-15T09:30:00Z",
		),
	}
	invocationErr := client.Campaigns.CreateActionSchedule(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionScheduleWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionScheduleWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/schedule", nil, 1)
}

func TestCampaignsCreateActionSendWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionSendCampaignsRequest{
		CampaignID: "campaign_id",
	}
	invocationErr := client.Campaigns.CreateActionSend(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionSendWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionSendWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/send", nil, 1)
}

func TestCampaignsCreateActionTestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionTestCampaignsRequest{
		CampaignID: "campaign_id",
		SendType:   mailchimpmarketinggosdk.CreateActionTestCampaignsRequestSendTypeHTML,
		TestEmails: []string{
			"test_emails",
		},
	}
	invocationErr := client.Campaigns.CreateActionTest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionTestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionTestWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/test", nil, 1)
}

func TestCampaignsCreateActionUnscheduleWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateActionUnscheduleCampaignsRequest{
		CampaignID: "campaign_id",
	}
	invocationErr := client.Campaigns.CreateActionUnschedule(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateActionUnscheduleWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateActionUnscheduleWithWireMock", "POST", "/3.0/campaigns/campaign_id/actions/unschedule", nil, 1)
}

func TestCampaignsGetContentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetContentCampaignsRequest{
		CampaignID: "campaign_id",
	}
	_, invocationErr := client.Campaigns.GetContent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsGetContentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsGetContentWithWireMock", "GET", "/3.0/campaigns/campaign_id/content", nil, 1)
}

func TestCampaignsUpsertContentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpsertContentCampaignsRequest{
		CampaignID: "campaign_id",
		Body:       &mailchimpmarketinggosdk.CampaignContent{},
	}
	_, invocationErr := client.Campaigns.UpsertContent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsUpsertContentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsUpsertContentWithWireMock", "PUT", "/3.0/campaigns/campaign_id/content", nil, 1)
}

func TestCampaignsListFeedbackWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListFeedbackCampaignsRequest{
		CampaignID: "campaign_id",
	}
	_, invocationErr := client.Campaigns.ListFeedback(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsListFeedbackWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsListFeedbackWithWireMock", "GET", "/3.0/campaigns/campaign_id/feedback", nil, 1)
}

func TestCampaignsCreateFeedbackWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.CreateFeedbackCampaignsRequest{
		CampaignID: "campaign_id",
		Message:    "message",
	}
	_, invocationErr := client.Campaigns.CreateFeedback(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsCreateFeedbackWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsCreateFeedbackWithWireMock", "POST", "/3.0/campaigns/campaign_id/feedback", nil, 1)
}

func TestCampaignsGetFeedbackWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.GetFeedbackCampaignsRequest{
		CampaignID: "campaign_id",
		FeedbackID: "feedback_id",
	}
	_, invocationErr := client.Campaigns.GetFeedback(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsGetFeedbackWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsGetFeedbackWithWireMock", "GET", "/3.0/campaigns/campaign_id/feedback/feedback_id", nil, 1)
}

func TestCampaignsDeleteFeedbackWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.DeleteFeedbackCampaignsRequest{
		CampaignID: "campaign_id",
		FeedbackID: "feedback_id",
	}
	invocationErr := client.Campaigns.DeleteFeedback(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsDeleteFeedbackWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsDeleteFeedbackWithWireMock", "DELETE", "/3.0/campaigns/campaign_id/feedback/feedback_id", nil, 1)
}

func TestCampaignsUpdateFeedbackWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.UpdateFeedbackCampaignsRequest{
		CampaignID: "campaign_id",
		FeedbackID: "feedback_id",
	}
	_, invocationErr := client.Campaigns.UpdateFeedback(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsUpdateFeedbackWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsUpdateFeedbackWithWireMock", "PATCH", "/3.0/campaigns/campaign_id/feedback/feedback_id", nil, 1)
}

func TestCampaignsListSendChecklistWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewMailchimpClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &mailchimpmarketinggosdk.ListSendChecklistCampaignsRequest{
		CampaignID: "campaign_id",
	}
	_, invocationErr := client.Campaigns.ListSendChecklist(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCampaignsListSendChecklistWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCampaignsListSendChecklistWithWireMock", "GET", "/3.0/campaigns/campaign_id/send-checklist", nil, 1)
}
