// Code generated by Fern. DO NOT EDIT.

package connectedsites

import (
	context "context"
	fmt "fmt"
	http "net/http"
	strconv "strconv"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get all connected sites in an account.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListConnectedSitesRequest{}
//	client.ConnectedSites.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListConnectedSitesRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ConnectedSite, *mailchimpmarketinggosdk.ListConnectedSitesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/connected-sites"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListConnectedSitesResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ConnectedSite, *mailchimpmarketinggosdk.ListConnectedSitesResponse] {
		next += 1
		results := response.GetSites()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ConnectedSite, *mailchimpmarketinggosdk.ListConnectedSitesResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Create a new Mailchimp connected site.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateConnectedSitesRequest{
//	    Domain: "example.com",
//	    ForeignID: "MC001",
//	}
//	client.ConnectedSites.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateConnectedSitesRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ConnectedSite, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific connected site.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetConnectedSitesRequest{
//	    ConnectedSiteID: "connected_site_id",
//	}
//	client.ConnectedSites.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetConnectedSitesRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ConnectedSite, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove a connected site from your Mailchimp account.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteConnectedSitesRequest{
//	    ConnectedSiteID: "connected_site_id",
//	}
//	client.ConnectedSites.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteConnectedSitesRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Verify that the connected sites script has been installed, either via the script URL or fragment.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateActionVerifyScriptInstallationConnectedSitesRequest{
//	    ConnectedSiteID: "connected_site_id",
//	}
//	client.ConnectedSites.CreateActionVerifyScriptInstallation(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateActionVerifyScriptInstallation(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateActionVerifyScriptInstallationConnectedSitesRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CreateActionVerifyScriptInstallation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
