// Code generated by Fern. DO NOT EDIT.

package ecommerce

import (
	context "context"
	http "net/http"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ListEcommerceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/ecommerce"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ListEcommerceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ListEcommerceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStore(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceStore], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/ecommerce/stores"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceStore
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceStore]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStore(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceStore], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v",
		request.StoreID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceStore
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceStore]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStore(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v",
		request.StoreID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStore(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceStore], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v",
		request.StoreID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceStore
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceStore]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreCart(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreCartEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCart], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts",
		request.StoreID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceCart
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCart]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreCart(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreCartEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCart], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts/%v",
		request.StoreID,
		request.CartID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceCart
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCart]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreCart(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreCartEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts/%v",
		request.StoreID,
		request.CartID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreCart(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreCartEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCart], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts/%v",
		request.StoreID,
		request.CartID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceCart
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCart]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreCartLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreCartLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCartLineItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts/%v/lines",
		request.StoreID,
		request.CartID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceCartLineItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCartLineItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreCartLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreCartLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCartLineItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts/%v/lines/%v",
		request.StoreID,
		request.CartID,
		request.LineID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceCartLineItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCartLineItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreCartLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreCartLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts/%v/lines/%v",
		request.StoreID,
		request.CartID,
		request.LineID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreCartLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreCartLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCartLineItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/carts/%v/lines/%v",
		request.StoreID,
		request.CartID,
		request.LineID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceCartLineItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCartLineItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreCustomer(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreCustomerEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCustomer], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/customers",
		request.StoreID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceCustomer
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCustomer]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreCustomer(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreCustomerEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCustomer], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/customers/%v",
		request.StoreID,
		request.CustomerID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceCustomer
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCustomer]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpsertStoreCustomer(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpsertStoreCustomerEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCustomer], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/customers/%v",
		request.StoreID,
		request.CustomerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceCustomer
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCustomer]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreCustomer(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreCustomerEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/customers/%v",
		request.StoreID,
		request.CustomerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreCustomer(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreCustomerEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceCustomer], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/customers/%v",
		request.StoreID,
		request.CustomerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceCustomer
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceCustomer]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreOrder(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreOrderEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceOrder], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders",
		request.StoreID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceOrder
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceOrder]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreOrder(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreOrderEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceOrder], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders/%v",
		request.StoreID,
		request.OrderID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceOrder
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceOrder]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreOrder(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreOrderEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders/%v",
		request.StoreID,
		request.OrderID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreOrder(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreOrderEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceOrder], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders/%v",
		request.StoreID,
		request.OrderID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceOrder
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceOrder]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreOrderLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreOrderLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceOrderLineItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders/%v/lines",
		request.StoreID,
		request.OrderID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceOrderLineItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceOrderLineItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreOrderLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreOrderLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceOrderLineItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders/%v/lines/%v",
		request.StoreID,
		request.OrderID,
		request.LineID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceOrderLineItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceOrderLineItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreOrderLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreOrderLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders/%v/lines/%v",
		request.StoreID,
		request.OrderID,
		request.LineID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreOrderLine(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreOrderLineEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceOrderLineItem], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/orders/%v/lines/%v",
		request.StoreID,
		request.OrderID,
		request.LineID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceOrderLineItem
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceOrderLineItem]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreProduct(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreProductEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProduct], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products",
		request.StoreID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceProduct
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProduct]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreProduct(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreProductEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProduct], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v",
		request.StoreID,
		request.ProductID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceProduct
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProduct]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpsertStoreProduct(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpsertStoreProductEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProduct], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v",
		request.StoreID,
		request.ProductID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceProduct
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProduct]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreProduct(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreProductEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v",
		request.StoreID,
		request.ProductID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreProduct(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreProductEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProduct], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v",
		request.StoreID,
		request.ProductID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceProduct
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProduct]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreProductImage(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreProductImageEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.CreateStoreProductImageEcommerceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/images",
		request.StoreID,
		request.ProductID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.CreateStoreProductImageEcommerceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.CreateStoreProductImageEcommerceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreProductImage(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreProductImageEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.GetStoreProductImageEcommerceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/images/%v",
		request.StoreID,
		request.ProductID,
		request.ImageID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.GetStoreProductImageEcommerceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.GetStoreProductImageEcommerceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreProductImage(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreProductImageEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/images/%v",
		request.StoreID,
		request.ProductID,
		request.ImageID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreProductImage(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreProductImageEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.UpdateStoreProductImageEcommerceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/images/%v",
		request.StoreID,
		request.ProductID,
		request.ImageID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.UpdateStoreProductImageEcommerceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.UpdateStoreProductImageEcommerceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStoreProductVariant(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStoreProductVariantEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/variants",
		request.StoreID,
		request.ProductID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceProductVariant
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStoreProductVariant(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStoreProductVariantEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/variants/%v",
		request.StoreID,
		request.ProductID,
		request.VariantID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommerceProductVariant
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpsertStoreProductVariant(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpsertStoreProductVariantEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/variants/%v",
		request.StoreID,
		request.ProductID,
		request.VariantID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceProductVariant
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStoreProductVariant(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStoreProductVariantEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/variants/%v",
		request.StoreID,
		request.ProductID,
		request.VariantID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStoreProductVariant(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStoreProductVariantEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/products/%v/variants/%v",
		request.StoreID,
		request.ProductID,
		request.VariantID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommerceProductVariant
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommerceProductVariant]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStorePromoRule(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStorePromoRuleEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommercePromoRule], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules",
		request.StoreID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommercePromoRule
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommercePromoRule]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStorePromoRule(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStorePromoRuleEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommercePromoRule], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules/%v",
		request.StoreID,
		request.PromoRuleID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommercePromoRule
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommercePromoRule]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStorePromoRule(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStorePromoRuleEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules/%v",
		request.StoreID,
		request.PromoRuleID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStorePromoRule(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStorePromoRuleEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommercePromoRule], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules/%v",
		request.StoreID,
		request.PromoRuleID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommercePromoRule
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommercePromoRule]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateStorePromoRulePromoCode(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateStorePromoRulePromoCodeEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommercePromoCode], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules/%v/promo-codes",
		request.StoreID,
		request.PromoRuleID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommercePromoCode
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommercePromoCode]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetStorePromoRulePromoCode(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetStorePromoRulePromoCodeEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommercePromoCode], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules/%v/promo-codes/%v",
		request.StoreID,
		request.PromoRuleID,
		request.PromoCodeID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ECommercePromoCode
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommercePromoCode]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteStorePromoRulePromoCode(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteStorePromoRulePromoCodeEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules/%v/promo-codes/%v",
		request.StoreID,
		request.PromoRuleID,
		request.PromoCodeID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) UpdateStorePromoRulePromoCode(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateStorePromoRulePromoCodeEcommerceRequest,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ECommercePromoCode], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/ecommerce/stores/%v/promo-rules/%v/promo-codes/%v",
		request.StoreID,
		request.PromoRuleID,
		request.PromoCodeID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *mailchimpmarketinggosdk.ECommercePromoCode
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ECommercePromoCode]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
