// Code generated by Fern. DO NOT EDIT.

package ping

import (
	context "context"
	http "net/http"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*mailchimpmarketinggosdk.ListPingResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/ping"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mailchimpmarketinggosdk.ListPingResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mailchimpmarketinggosdk.ListPingResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
