// Code generated by Fern. DO NOT EDIT.

package lists

import (
	context "context"
	fmt "fmt"
	http "net/http"
	strconv "strconv"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get information about all lists in the account.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListListsRequest{}
//	client.Lists.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.SubscriberList, *mailchimpmarketinggosdk.ListListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/lists"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.SubscriberList, *mailchimpmarketinggosdk.ListListsResponse] {
		next += 1
		results := response.GetLists()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.SubscriberList, *mailchimpmarketinggosdk.ListListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Create a new list in your Mailchimp account.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateListsRequest{
//	    CampaignDefaults: &mailchimpmarketinggosdk.CreateListsRequestCampaignDefaults{
//	        FromEmail: "from_email",
//	        FromName: "from_name",
//	        Language: "language",
//	        Subject: "subject",
//	    },
//	    Contact: &mailchimpmarketinggosdk.CreateListsRequestContact{
//	        Address1: "address1",
//	        City: "city",
//	        Company: "company",
//	        Country: "country",
//	    },
//	    EmailTypeOption: true,
//	    Name: "name",
//	    PermissionReminder: "permission_reminder",
//	}
//	client.Lists.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.SubscriberList, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific list in your Mailchimp account. Results include list members who have signed up but haven't confirmed their subscription yet and unsubscribed or cleaned.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.SubscriberList, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Batch subscribe or unsubscribe list members.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.BatchSubscribeOrUnsubscribeListsRequest{
//	    ListID: "list_id",
//	    Members: []*mailchimpmarketinggosdk.BatchSubscribeOrUnsubscribeListsRequestMembersItem{},
//	}
//	client.Lists.BatchSubscribeOrUnsubscribe(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) BatchSubscribeOrUnsubscribe(
	ctx context.Context,
	request *mailchimpmarketinggosdk.BatchSubscribeOrUnsubscribeListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.BatchSubscribeOrUnsubscribeListsResponse, error) {
	response, err := c.WithRawResponse.BatchSubscribeOrUnsubscribe(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a list from your Mailchimp account. If you delete a list, you'll lose the list history—including subscriber activity, unsubscribes, complaints, and bounces. You’ll also lose subscribers’ email addresses, unless you exported and backed up your list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update the settings for a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.SubscriberList, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get all abuse reports for a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListAbuseReportsListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListAbuseReports(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListAbuseReports(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListAbuseReportsListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ListsAbuseReports, *mailchimpmarketinggosdk.ListAbuseReportsListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/abuse-reports",
		request.ListID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListAbuseReportsListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ListsAbuseReports, *mailchimpmarketinggosdk.ListAbuseReportsListsResponse] {
		next += 1
		results := response.GetAbuseReports()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ListsAbuseReports, *mailchimpmarketinggosdk.ListAbuseReportsListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Get details about a specific abuse report.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetAbuseReportListsRequest{
//	    ListID: "list_id",
//	    ReportID: "report_id",
//	}
//	client.Lists.GetAbuseReport(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetAbuseReport(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetAbuseReportListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListsAbuseReports, error) {
	response, err := c.WithRawResponse.GetAbuseReport(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get up to the previous 180 days of daily detailed aggregated activity stats for a list, not including Automation activity.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListActivityListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListActivity(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListActivity(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListActivityListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ListActivityListsResponseActivityItem, *mailchimpmarketinggosdk.ListActivityListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/activity",
		request.ListID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListActivityListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ListActivityListsResponseActivityItem, *mailchimpmarketinggosdk.ListActivityListsResponse] {
		next += 1
		results := response.GetActivity()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ListActivityListsResponseActivityItem, *mailchimpmarketinggosdk.ListActivityListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Get a list of the top email clients based on user-agent strings.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListClientsListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListClients(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListClients(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListClientsListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListClientsListsResponse, error) {
	response, err := c.WithRawResponse.ListClients(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a month-by-month summary of a specific list's growth activity.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListGrowthHistoryListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListGrowthHistory(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListGrowthHistory(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListGrowthHistoryListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.GrowthHistory, *mailchimpmarketinggosdk.ListGrowthHistoryListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/growth-history",
		request.ListID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListGrowthHistoryListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.GrowthHistory, *mailchimpmarketinggosdk.ListGrowthHistoryListsResponse] {
		next += 1
		results := response.GetHistory()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.GrowthHistory, *mailchimpmarketinggosdk.ListGrowthHistoryListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Get a summary of a specific list's growth activity for a specific month and year.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetGrowthHistoryListsRequest{
//	    ListID: "list_id",
//	    Month: "month",
//	}
//	client.Lists.GetGrowthHistory(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetGrowthHistory(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetGrowthHistoryListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.GrowthHistory, error) {
	response, err := c.WithRawResponse.GetGrowthHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a list's interest categories.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListInterestCategoriesListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListInterestCategories(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListInterestCategories(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListInterestCategoriesListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.InterestCategory, *mailchimpmarketinggosdk.ListInterestCategoriesListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/interest-categories",
		request.ListID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListInterestCategoriesListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.InterestCategory, *mailchimpmarketinggosdk.ListInterestCategoriesListsResponse] {
		next += 1
		results := response.GetCategories()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.InterestCategory, *mailchimpmarketinggosdk.ListInterestCategoriesListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Create a new interest category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateInterestCategoryListsRequest{
//	    ListID: "list_id",
//	    Title: "title",
//	    Type: mailchimpmarketinggosdk.CreateInterestCategoryListsRequestTypeCheckboxes,
//	}
//	client.Lists.CreateInterestCategory(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateInterestCategory(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateInterestCategoryListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.InterestCategory, error) {
	response, err := c.WithRawResponse.CreateInterestCategory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific interest category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetInterestCategoryListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	}
//	client.Lists.GetInterestCategory(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetInterestCategory(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetInterestCategoryListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.InterestCategory, error) {
	response, err := c.WithRawResponse.GetInterestCategory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific interest category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteInterestCategoryListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	}
//	client.Lists.DeleteInterestCategory(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteInterestCategory(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteInterestCategoryListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteInterestCategory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update a specific interest category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateInterestCategoryListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	}
//	client.Lists.UpdateInterestCategory(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateInterestCategory(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateInterestCategoryListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.InterestCategory, error) {
	response, err := c.WithRawResponse.UpdateInterestCategory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a list of this category's interests.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListInterestCategoryInterestsListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	}
//	client.Lists.ListInterestCategoryInterests(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListInterestCategoryInterests(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListInterestCategoryInterestsListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.Interest, *mailchimpmarketinggosdk.ListInterestCategoryInterestsListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/interest-categories/%v/interests",
		request.ListID,
		request.InterestCategoryID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListInterestCategoryInterestsListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.Interest, *mailchimpmarketinggosdk.ListInterestCategoryInterestsListsResponse] {
		next += 1
		results := response.GetInterests()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.Interest, *mailchimpmarketinggosdk.ListInterestCategoryInterestsListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Create a new interest or 'group name' for a specific category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateInterestCategoryInterestListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	    Name: "name",
//	}
//	client.Lists.CreateInterestCategoryInterest(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateInterestCategoryInterest(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateInterestCategoryInterestListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.Interest, error) {
	response, err := c.WithRawResponse.CreateInterestCategoryInterest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get interests or 'group names' for a specific category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetInterestCategoryInterestListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	    InterestID: "interest_id",
//	}
//	client.Lists.GetInterestCategoryInterest(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetInterestCategoryInterest(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetInterestCategoryInterestListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.Interest, error) {
	response, err := c.WithRawResponse.GetInterestCategoryInterest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete interests or group names in a specific category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteInterestCategoryInterestListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	    InterestID: "interest_id",
//	}
//	client.Lists.DeleteInterestCategoryInterest(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteInterestCategoryInterest(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteInterestCategoryInterestListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteInterestCategoryInterest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update interests or 'group names' for a specific category.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateInterestCategoryInterestListsRequest{
//	    ListID: "list_id",
//	    InterestCategoryID: "interest_category_id",
//	    InterestID: "interest_id",
//	}
//	client.Lists.UpdateInterestCategoryInterest(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateInterestCategoryInterest(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateInterestCategoryInterestListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.Interest, error) {
	response, err := c.WithRawResponse.UpdateInterestCategoryInterest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the locations (countries) that the list's subscribers have been tagged to based on geocoding their IP address.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListLocationsListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListLocations(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListLocations(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListLocationsListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListLocationsListsResponse, error) {
	response, err := c.WithRawResponse.ListLocations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about members in a specific Mailchimp list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMembersListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListMembers(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMembers(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMembersListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ListMembers, *mailchimpmarketinggosdk.ListMembersListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/members",
		request.ListID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListMembersListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ListMembers, *mailchimpmarketinggosdk.ListMembersListsResponse] {
		next += 1
		results := response.GetMembers()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ListMembers, *mailchimpmarketinggosdk.ListMembersListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Add a new member to the list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateMemberListsRequest{
//	    ListID: "list_id",
//	    EmailAddress: "email_address",
//	    Status: mailchimpmarketinggosdk.CreateMemberListsRequestStatusSubscribed,
//	}
//	client.Lists.CreateMember(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateMember(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateMemberListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListMembers, error) {
	response, err := c.WithRawResponse.CreateMember(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific list member, including a currently subscribed, unsubscribed, or bounced member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetMemberListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.GetMember(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetMember(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetMemberListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListMembers, error) {
	response, err := c.WithRawResponse.GetMember(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Add or update a list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpsertMemberListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	    EmailAddress: "email_address",
//	}
//	client.Lists.UpsertMember(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpsertMember(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpsertMemberListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListMembers, error) {
	response, err := c.WithRawResponse.UpsertMember(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Archive a list member. To permanently delete, use the delete-permanent action.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteMemberListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.DeleteMember(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteMember(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteMemberListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteMember(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update information for a specific list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateMemberListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.UpdateMember(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateMember(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateMemberListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListMembers, error) {
	response, err := c.WithRawResponse.UpdateMember(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete all personally identifiable information related to a list member, and remove them from a list. This will make it impossible to re-import the list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateMemberActionDeletePermanentListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.CreateMemberActionDeletePermanent(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateMemberActionDeletePermanent(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateMemberActionDeletePermanentListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CreateMemberActionDeletePermanent(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Get the last 50 events of a member's activity on a specific list, including opens, clicks, and unsubscribes.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMemberActivityListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.ListMemberActivity(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMemberActivity(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMemberActivityListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListMemberActivityListsResponse, error) {
	response, err := c.WithRawResponse.ListMemberActivity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a member's activity on a specific list, including opens, clicks, and unsubscribes.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMemberActivityFeedListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.ListMemberActivityFeed(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMemberActivityFeed(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMemberActivityFeedListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, any, *mailchimpmarketinggosdk.ListMemberActivityFeedListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/members/%v/activity-feed",
		request.ListID,
		request.SubscriberHash,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListMemberActivityFeedListsResponse) *core.PageResponse[*int, any, *mailchimpmarketinggosdk.ListMemberActivityFeedListsResponse] {
		next += 1
		results := response.GetActivity()
		return &core.PageResponse[*int, any, *mailchimpmarketinggosdk.ListMemberActivityFeedListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Get events for a contact.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMemberEventsListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.ListMemberEvents(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMemberEvents(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMemberEventsListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ListMemberEventsListsResponseEventsItem, *mailchimpmarketinggosdk.ListMemberEventsListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/members/%v/events",
		request.ListID,
		request.SubscriberHash,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListMemberEventsListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ListMemberEventsListsResponseEventsItem, *mailchimpmarketinggosdk.ListMemberEventsListsResponse] {
		next += 1
		results := response.GetEvents()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ListMemberEventsListsResponseEventsItem, *mailchimpmarketinggosdk.ListMemberEventsListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Add an event for a list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateMemberEventListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	    Name: "name",
//	}
//	client.Lists.CreateMemberEvent(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateMemberEvent(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateMemberEventListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CreateMemberEvent(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Get the last 50 Goal events for a member on a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMemberGoalsListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.ListMemberGoals(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMemberGoals(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMemberGoalsListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListMemberGoalsListsResponse, error) {
	response, err := c.WithRawResponse.ListMemberGoals(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get recent notes for a specific list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMemberNotesListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.ListMemberNotes(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMemberNotes(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMemberNotesListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.MemberNotes, *mailchimpmarketinggosdk.ListMemberNotesListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/members/%v/notes",
		request.ListID,
		request.SubscriberHash,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListMemberNotesListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.MemberNotes, *mailchimpmarketinggosdk.ListMemberNotesListsResponse] {
		next += 1
		results := response.GetNotes()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.MemberNotes, *mailchimpmarketinggosdk.ListMemberNotesListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Add a new note for a specific subscriber.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateMemberNoteListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.CreateMemberNote(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateMemberNote(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateMemberNoteListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.MemberNotes, error) {
	response, err := c.WithRawResponse.CreateMemberNote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a specific note for a specific list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetMemberNoteListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	    NoteID: "note_id",
//	}
//	client.Lists.GetMemberNote(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetMemberNote(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetMemberNoteListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.MemberNotes, error) {
	response, err := c.WithRawResponse.GetMemberNote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific note for a specific list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteMemberNoteListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	    NoteID: "note_id",
//	}
//	client.Lists.DeleteMemberNote(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteMemberNote(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteMemberNoteListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteMemberNote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update a specific note for a specific list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateMemberNoteListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	    NoteID: "note_id",
//	}
//	client.Lists.UpdateMemberNote(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateMemberNote(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateMemberNoteListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.MemberNotes, error) {
	response, err := c.WithRawResponse.UpdateMemberNote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the tags on a list member.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMemberTagsListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.ListMemberTags(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMemberTags(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMemberTagsListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ListMemberTagsListsResponseTagsItem, *mailchimpmarketinggosdk.ListMemberTagsListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/members/%v/tags",
		request.ListID,
		request.SubscriberHash,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListMemberTagsListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ListMemberTagsListsResponseTagsItem, *mailchimpmarketinggosdk.ListMemberTagsListsResponse] {
		next += 1
		results := response.GetTags()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ListMemberTagsListsResponseTagsItem, *mailchimpmarketinggosdk.ListMemberTagsListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Add or remove tags from a list member. If a tag that does not exist is passed in and set as 'active', a new tag will be created.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateMemberTagListsRequest{
//	    ListID: "list_id",
//	    SubscriberHash: "subscriber_hash",
//	    Tags: []*mailchimpmarketinggosdk.CreateMemberTagListsRequestTagsItem{
//	        &mailchimpmarketinggosdk.CreateMemberTagListsRequestTagsItem{
//	            Name: "name",
//	            Status: mailchimpmarketinggosdk.CreateMemberTagListsRequestTagsItemStatusInactive,
//	        },
//	    },
//	}
//	client.Lists.CreateMemberTag(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateMemberTag(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateMemberTagListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CreateMemberTag(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Get a list of all merge fields for an audience.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListMergeFieldsListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListMergeFields(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMergeFields(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListMergeFieldsListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.MergeField, *mailchimpmarketinggosdk.ListMergeFieldsListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/merge-fields",
		request.ListID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListMergeFieldsListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.MergeField, *mailchimpmarketinggosdk.ListMergeFieldsListsResponse] {
		next += 1
		results := response.GetMergeFields()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.MergeField, *mailchimpmarketinggosdk.ListMergeFieldsListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Add a new merge field for a specific audience.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateMergeFieldListsRequest{
//	    ListID: "list_id",
//	    Name: "name",
//	    Type: mailchimpmarketinggosdk.CreateMergeFieldListsRequestTypeText,
//	}
//	client.Lists.CreateMergeField(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateMergeField(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateMergeFieldListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.MergeField, error) {
	response, err := c.WithRawResponse.CreateMergeField(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific merge field.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetMergeFieldListsRequest{
//	    ListID: "list_id",
//	    MergeID: "merge_id",
//	}
//	client.Lists.GetMergeField(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetMergeField(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetMergeFieldListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.MergeField, error) {
	response, err := c.WithRawResponse.GetMergeField(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific merge field.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteMergeFieldListsRequest{
//	    ListID: "list_id",
//	    MergeID: "merge_id",
//	}
//	client.Lists.DeleteMergeField(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteMergeField(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteMergeFieldListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteMergeField(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update a specific merge field.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateMergeFieldListsRequest{
//	    ListID: "list_id",
//	    MergeID: "merge_id",
//	}
//	client.Lists.UpdateMergeField(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateMergeField(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateMergeFieldListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.MergeField, error) {
	response, err := c.WithRawResponse.UpdateMergeField(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about all available segments for a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListSegmentsListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListSegments(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListSegments(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListSegmentsListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.List, *mailchimpmarketinggosdk.ListSegmentsListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/segments",
		request.ListID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListSegmentsListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.List, *mailchimpmarketinggosdk.ListSegmentsListsResponse] {
		next += 1
		results := response.GetSegments()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.List, *mailchimpmarketinggosdk.ListSegmentsListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Create a new segment in a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateSegmentListsRequest{
//	    ListID: "list_id",
//	    Name: "name",
//	}
//	client.Lists.CreateSegment(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateSegment(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateSegmentListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.List, error) {
	response, err := c.WithRawResponse.CreateSegment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific segment.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetSegmentListsRequest{
//	    ListID: "list_id",
//	    SegmentID: "segment_id",
//	}
//	client.Lists.GetSegment(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetSegment(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetSegmentListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.List, error) {
	response, err := c.WithRawResponse.GetSegment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Batch add/remove list members to static segment
//
// Example:
//
//	request := &mailchimpmarketinggosdk.BatchAddOrRemoveMembersListsRequest{
//	    ListID: "list_id",
//	    SegmentID: "segment_id",
//	}
//	client.Lists.BatchAddOrRemoveMembers(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) BatchAddOrRemoveMembers(
	ctx context.Context,
	request *mailchimpmarketinggosdk.BatchAddOrRemoveMembersListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.BatchAddOrRemoveMembersListsResponse, error) {
	response, err := c.WithRawResponse.BatchAddOrRemoveMembers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific segment in a list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteSegmentListsRequest{
//	    ListID: "list_id",
//	    SegmentID: "segment_id",
//	}
//	client.Lists.DeleteSegment(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteSegment(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteSegmentListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteSegment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update a specific segment in a list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateSegmentListsRequest{
//	    ListID: "list_id",
//	    SegmentID: "segment_id",
//	}
//	client.Lists.UpdateSegment(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateSegment(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateSegmentListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.List, error) {
	response, err := c.WithRawResponse.UpdateSegment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about members in a saved segment.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListSegmentMembersListsRequest{
//	    ListID: "list_id",
//	    SegmentID: "segment_id",
//	}
//	client.Lists.ListSegmentMembers(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListSegmentMembers(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListSegmentMembersListsRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.ListsSegmentsMembers, *mailchimpmarketinggosdk.ListSegmentMembersListsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/3.0/lists/%v/segments/%v/members",
		request.ListID,
		request.SegmentID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListSegmentMembersListsResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.ListsSegmentsMembers, *mailchimpmarketinggosdk.ListSegmentMembersListsResponse] {
		next += 1
		results := response.GetMembers()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.ListsSegmentsMembers, *mailchimpmarketinggosdk.ListSegmentMembersListsResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Add a member to a static segment.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateSegmentMemberListsRequest{
//	    ListID: "list_id",
//	    SegmentID: "segment_id",
//	    EmailAddress: "email_address",
//	}
//	client.Lists.CreateSegmentMember(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateSegmentMember(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateSegmentMemberListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListsSegmentsMembers, error) {
	response, err := c.WithRawResponse.CreateSegmentMember(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove a member from the specified static segment.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteSegmentMemberListsRequest{
//	    ListID: "list_id",
//	    SegmentID: "segment_id",
//	    SubscriberHash: "subscriber_hash",
//	}
//	client.Lists.DeleteSegmentMember(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteSegmentMember(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteSegmentMemberListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteSegmentMember(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Get signup forms for a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListSignupFormsListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListSignupForms(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListSignupForms(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListSignupFormsListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListSignupFormsListsResponse, error) {
	response, err := c.WithRawResponse.ListSignupForms(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Customize a list's default signup form.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateSignupFormListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.CreateSignupForm(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateSignupForm(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateSignupFormListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.SignupForm, error) {
	response, err := c.WithRawResponse.CreateSignupForm(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about all available surveys for a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListSurveysListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListSurveys(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListSurveys(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListSurveysListsRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.ListSurveys(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a draft survey for an audience.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateSurveyListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.CreateSurvey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateSurvey(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateSurveyListsRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.CreateSurvey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get details about a specific survey.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetSurveyListsRequest{
//	    ListID: "list_id",
//	    SurveyID: "survey_id",
//	}
//	client.Lists.GetSurvey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetSurvey(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetSurveyListsRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.GetSurvey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a survey.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteSurveyListsRequest{
//	    ListID: "list_id",
//	    SurveyID: "survey_id",
//	}
//	client.Lists.DeleteSurvey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteSurvey(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteSurveyListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteSurvey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update a survey. When sections is provided, send the complete section list in display order. Any existing section not included is deleted.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateSurveyListsRequest{
//	    ListID: "list_id",
//	    SurveyID: "survey_id",
//	}
//	client.Lists.UpdateSurvey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateSurvey(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateSurveyListsRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.UpdateSurvey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Replicate a survey.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateListSurveyActionReplicateListsRequest{
//	    ListIDPathParam: "list_id",
//	    SurveyID: "survey_id",
//	}
//	client.Lists.CreateListSurveyActionReplicate(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateListSurveyActionReplicate(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateListSurveyActionReplicateListsRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.CreateListSurveyActionReplicate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Search for tags on a list by name. If no name is provided, will return all tags on the list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListTagSearchListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListTagSearch(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListTagSearch(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListTagSearchListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListTagSearchListsResponse, error) {
	response, err := c.WithRawResponse.ListTagSearch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about all webhooks for a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListWebhooksListsRequest{
//	    ListID: "list_id",
//	}
//	client.Lists.ListWebhooks(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListWebhooks(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListWebhooksListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListWebhooksListsResponse, error) {
	response, err := c.WithRawResponse.ListWebhooks(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new webhook for a specific list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateWebhookListsRequest{
//	    ListID: "list_id",
//	    Body: &mailchimpmarketinggosdk.AddWebhook{},
//	}
//	client.Lists.CreateWebhook(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateWebhook(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateWebhookListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListWebhooks, error) {
	response, err := c.WithRawResponse.CreateWebhook(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific webhook.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetWebhookListsRequest{
//	    ListID: "list_id",
//	    WebhookID: "webhook_id",
//	}
//	client.Lists.GetWebhook(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetWebhook(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetWebhookListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListWebhooks, error) {
	response, err := c.WithRawResponse.GetWebhook(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific webhook in a list.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteWebhookListsRequest{
//	    ListID: "list_id",
//	    WebhookID: "webhook_id",
//	}
//	client.Lists.DeleteWebhook(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteWebhook(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteWebhookListsRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteWebhook(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update the settings for an existing webhook.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateWebhookListsRequest{
//	    ListID: "list_id",
//	    WebhookID: "webhook_id",
//	    Body: &mailchimpmarketinggosdk.AddWebhook{},
//	}
//	client.Lists.UpdateWebhook(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateWebhook(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateWebhookListsRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.ListWebhooks, error) {
	response, err := c.WithRawResponse.UpdateWebhook(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
