// Code generated by Fern. DO NOT EDIT.

package batchwebhooks

import (
	context "context"
	fmt "fmt"
	http "net/http"
	strconv "strconv"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get all webhooks that have been configured for batches.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListBatchWebhooksRequest{}
//	client.BatchWebhooks.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListBatchWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.BatchWebhook, *mailchimpmarketinggosdk.ListBatchWebhooksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/batch-webhooks"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListBatchWebhooksResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.BatchWebhook, *mailchimpmarketinggosdk.ListBatchWebhooksResponse] {
		next += 1
		results := response.GetWebhooks()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.BatchWebhook, *mailchimpmarketinggosdk.ListBatchWebhooksResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Configure a webhook that will fire whenever any batch request completes processing.  You may only have a maximum of 20 batch webhooks.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateBatchWebhooksRequest{
//	    URL: "http://yourdomain.com/webhook",
//	}
//	client.BatchWebhooks.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateBatchWebhooksRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.BatchWebhook, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about a specific batch webhook.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetBatchWebhooksRequest{
//	    BatchWebhookID: "batch_webhook_id",
//	}
//	client.BatchWebhooks.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetBatchWebhooksRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.BatchWebhook, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove a batch webhook. Webhooks will no longer be sent to the given URL.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteBatchWebhooksRequest{
//	    BatchWebhookID: "batch_webhook_id",
//	}
//	client.BatchWebhooks.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteBatchWebhooksRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update a webhook that will fire whenever any batch request completes processing.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.UpdateBatchWebhooksRequest{
//	    BatchWebhookID: "batch_webhook_id",
//	}
//	client.BatchWebhooks.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *mailchimpmarketinggosdk.UpdateBatchWebhooksRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.BatchWebhook, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
