// Code generated by Fern. DO NOT EDIT.

package batches

import (
	context "context"
	fmt "fmt"
	http "net/http"
	strconv "strconv"

	mailchimpmarketinggosdk "github.com/mailchimp/mailchimp-marketing-go-sdk"
	core "github.com/mailchimp/mailchimp-marketing-go-sdk/core"
	internal "github.com/mailchimp/mailchimp-marketing-go-sdk/internal"
	option "github.com/mailchimp/mailchimp-marketing-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get a summary of batch requests that have been made.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.ListBatchesRequest{}
//	client.Batches.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *mailchimpmarketinggosdk.ListBatchesRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *mailchimpmarketinggosdk.Batch, *mailchimpmarketinggosdk.ListBatchesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://us1.api.mailchimp.com",
	)
	endpointURL := baseURL + "/3.0/batches"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("offset", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
		}
	}
	next := 1
	if queryParams.Has("offset") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("offset")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *mailchimpmarketinggosdk.ListBatchesResponse) *core.PageResponse[*int, *mailchimpmarketinggosdk.Batch, *mailchimpmarketinggosdk.ListBatchesResponse] {
		next += 1
		results := response.GetBatches()
		return &core.PageResponse[*int, *mailchimpmarketinggosdk.Batch, *mailchimpmarketinggosdk.ListBatchesResponse]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

// Begin processing a batch operations request.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.CreateBatchesRequest{
//	    Operations: []*mailchimpmarketinggosdk.CreateBatchesRequestOperationsItem{
//	        &mailchimpmarketinggosdk.CreateBatchesRequestOperationsItem{
//	            Method: mailchimpmarketinggosdk.CreateBatchesRequestOperationsItemMethodGet,
//	            Path: "/lists",
//	        },
//	    },
//	}
//	client.Batches.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *mailchimpmarketinggosdk.CreateBatchesRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.Batch, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the status of a batch request.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.GetBatchesRequest{
//	    BatchID: "batch_id",
//	}
//	client.Batches.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *mailchimpmarketinggosdk.GetBatchesRequest,
	opts ...option.RequestOption,
) (*mailchimpmarketinggosdk.Batch, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Stops a batch request from running. Since only one batch request is run at a time, this can be used to cancel a long running request. The results of any completed operations will not be available after this call.
//
// Example:
//
//	request := &mailchimpmarketinggosdk.DeleteBatchesRequest{
//	    BatchID: "batch_id",
//	}
//	client.Batches.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *mailchimpmarketinggosdk.DeleteBatchesRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
